name = "code-push-server"
main = "src/index.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

d1_databases = [
  { binding = "DB", database_name = "code-push-server-local", database_id = "n/a", migrations_dir = "drizzle/migrations" },
]

[vars]
SERVER_URL = "http://localhost:8787"
ENABLE_ACCOUNT_REGISTRATION = "true"
CORS_ORIGINS = "http://localhost:5173"
ENABLE_PACKAGE_DIFFING = "true"

[[r2_buckets]]
binding = "STORAGE_BUCKET"
bucket_name = "code-push"
preview_bucket_name = "code-push-preview-2"

[env.preview]
d1_databases = [
  { binding = "DB", bucket_name = "code-push-preview-2", database_name = "code-push-preview", database_id = "bc787494-06b2-4cef-8621-b295f2d185e0", migrations_dir = "drizzle/migrations" },
]

[env.test]
d1_databases = [
  { binding = "DB", database_name = "code-push-preview", database_id = "bc787494-06b2-4cef-8621-b295f2d185e0", migrations_dir = "drizzle/migrations" },
]

[env.production]
d1_databases = [
  { binding = "DB", database_name = "code-push", database_id = "<id>", migrations_dir = "drizzle/migrations" },
]
